services:
  node-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}" 
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-db:/data/db # Named volume for persisting data
volumes:
  mongo-db: