services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://admin:admin@mongo:27017/?authSource=admin
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
       