services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db # Named volume for persisting data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mongo-db: